name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: gradle :app:assembleDebug

    - name: Analyze APK compatibility
      if: always()
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget

        ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip -q tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH

        # Instalar componentes necesarios (platform-tools + build-tools + platforms)
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "build-tools;34.0.0" "platforms;android-34"

        echo "== Listando APK generado =="
        ls -lh app/build/outputs/apk/debug/

        APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
        echo "== Usando APK: $APK_PATH =="

        echo "== SDK info =="
        apkanalyzer manifest min-sdk $APK_PATH
        apkanalyzer manifest target-sdk $APK_PATH

        echo "== Features =="
        apkanalyzer manifest features $APK_PATH

        echo "== Permisos =="
        apkanalyzer manifest permissions $APK_PATH


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tvbox-browser-debug
        path: app/build/outputs/apk/debug/*.apk
